# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses.
type: "java:8"
disk: 1024

# The hooks executed at various points in the lifecycle of the application.
hooks:
    build:  |
       rm -rf server/*
       rm -rf openkm.server.zip
       wget -q https://www.dropbox.com/s/hhcklafy589vfug/openkm.server.zip
       mkdir -p server
       unzip -o openkm.server.zip -d server/

mounts:
    '/server':
        source: local
        source_path: tomcat_server
    '/data':
        source: local
        source_path: data_path
# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
relationships:
    postgresdatabase: "dbpostgres:postgresql"

# The configuration of app when it is exposed to the web.
web:
    commands:
        start: |
          sh server/tomcat-8.5.34/bin/catalina.sh start
